# Generated by Django 3.2.6 on 2022-04-25 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0004_auto_20200517_1832'),
        ('post', '0002_post_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='categories',
            field=models.ManyToManyField(related_name='posts', to='categories.Category'),
        ),
    ]
