# Generated by Django 3.2.6 on 2022-06-07 20:01

import apps.tour.fields.summernote
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_auto_20220530_0206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=apps.tour.fields.summernote.SummernoteField(verbose_name='content'),
        ),
    ]
