# Generated by Django 3.2.7 on 2022-02-22 00:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_verificationcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='verificationcode',
            name='created_at',
        ),
        migrations.AddField(
            model_name='verificationcode',
            name='expire_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
