# Generated by Django 3.2.7 on 2022-03-19 00:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20220222_0031'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=200, verbose_name='fullname')),
                ('phonenumber', models.CharField(max_length=200, verbose_name='phonenumber')),
                ('state', models.CharField(max_length=200, verbose_name='state')),
                ('city', models.CharField(max_length=200, verbose_name='city')),
                ('address', models.CharField(max_length=500, verbose_name='address')),
                ('postal_code', models.CharField(max_length=200, verbose_name='postal code')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
