# Generated by Django 3.2.6 on 2021-09-13 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='name')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='email')),
                ('message', models.TextField(verbose_name='message')),
                ('phone_number', models.CharField(blank=True, max_length=128, null=True, verbose_name='phone number')),
                ('answer', models.TextField(blank=True, help_text='this text will send by email to user if email is filled', null=True, verbose_name='answer')),
                ('status', models.CharField(choices=[('unread', 'unread'), ('read', 'read'), ('answered', 'answered')], default='unread', max_length=8, verbose_name='status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
            ],
            options={
                'verbose_name': 'contact-us',
                'verbose_name_plural': 'contact-us messages',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
