# Generated by Django 3.2.7 on 2022-05-20 18:26

import django.db.models.deletion
from django.db import migrations

import apps.store.fields.store


class Migration(migrations.Migration):
    dependencies = [
        ('store', '0003_store_domain'),
        ('contactus', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='store',
            field=apps.store.fields.store.StoreField(null=True, on_delete=django.db.models.deletion.SET_NULL,
                                                     to='store.store', verbose_name='store'),
        ),
    ]
