# Generated by Django 3.2.6 on 2022-04-25 18:52

import apps.tour.fields.comma_sep
import apps.tour.fields.keyvalue_field
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='cancellation_rule',
            field=apps.tour.fields.comma_sep.CommaSepModelField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tour',
            name='room_details',
            field=apps.tour.fields.keyvalue_field.JsonKeyValueField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='services',
            field=apps.tour.fields.comma_sep.CommaSepModelField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='transportation',
            field=apps.tour.fields.keyvalue_field.JsonKeyValueField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='tour',
            name='geo_points',
            field=apps.tour.fields.comma_sep.CommaSepModelField(max_length=255),
        ),
    ]
