# Generated by Django 3.2.6 on 2022-04-29 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0002_auto_20220425_1852'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='age_range',
            field=models.CharField(default=1, help_text='eg. 18-50', max_length=10, verbose_name='age_range'),
            preserve_default=False,
        ),
    ]
