# Generated by Django 3.2.6 on 2022-04-29 20:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tour', '0003_tour_age_range'),
    ]

    operations = [
        migrations.CreateModel(
            name='TourRegistrar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PE', 'pending'), ('CO', 'completed'), ('CA', 'canceled')], default='PE', max_length=2)),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tour.tour')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='TourMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('birthdate', models.CharField(max_length=255)),
                ('born_country', models.CharField(max_length=255)),
                ('gender', models.CharField(choices=[('M', 'male'), ('F', 'female')], max_length=1)),
                ('passport_country', models.CharField(max_length=255)),
                ('passport_code', models.CharField(max_length=255)),
                ('passport_expired_at', models.CharField(max_length=255)),
                ('passport_issue', models.CharField(max_length=255)),
                ('registrar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tour.tourregistrar')),
            ],
            options={
                'verbose_name': 'tour member',
                'verbose_name_plural': 'tour members',
                'ordering': ('-id',),
            },
        ),
    ]
