# Generated by Django 3.2.6 on 2022-05-25 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0004_tourmember_tourregistrar'),
    ]

    operations = [
        migrations.CreateModel(
            name='TourDays',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('text', models.TextField(verbose_name='text')),
            ],
        ),
        migrations.AddField(
            model_name='tour',
            name='days',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tour.tourdays', verbose_name='tour days'),
        ),
    ]
