# Generated by Django 3.2.6 on 2022-05-29 20:57

import apps.tour.fields.summernote
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0007_auto_20220525_2138'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tour',
            old_name='transportation',
            new_name='features',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='room_details',
        ),
        migrations.AlterField(
            model_name='tour',
            name='age_range',
            field=models.CharField(help_text='eg. 18-50', max_length=10, verbose_name='age range'),
        ),
        migrations.AlterField(
            model_name='tourdays',
            name='text',
            field=apps.tour.fields.summernote.SummernoteField(verbose_name='text'),
        ),
        migrations.AlterField(
            model_name='touritinerary',
            name='content',
            field=apps.tour.fields.summernote.SummernoteField(verbose_name='answer'),
        ),
    ]
