# Generated by Django 3.2.6 on 2022-05-30 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0010_tour_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='as_featured',
            field=models.BooleanField(default=False, verbose_name='as featured tour'),
        ),
    ]
