# Generated by Django 3.2.6 on 2022-05-30 01:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0011_tour_as_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='touritinerary',
            name='tour',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='itinerary', to='tour.tour'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tour',
            name='slug',
            field=models.SlugField(max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='tourdays',
            name='tour',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='days', to='tour.tour', verbose_name='tour days'),
        ),
    ]
