# Generated by Django 3.2.6 on 2022-05-30 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('tour', '0011_tour_as_featured'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='categories',
            field=models.ManyToManyField(null=True, to='categories.Category'),
        ),
    ]
