# Generated by Django 3.2.6 on 2022-05-30 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('tour', '0012_alter_tour_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='categories',
            field=models.ManyToManyField(blank=True, null=True, to='categories.Category'),
        ),
    ]
