# Generated by Django 3.2.6 on 2022-05-30 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0012_auto_20220530_0133'),
        ('tour', '0013_alter_tour_categories'),
    ]

    operations = [
    ]
