# Generated by Django 3.2.6 on 2022-05-30 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0014_merge_20220530_0242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='slug',
            field=models.SlugField(default=1, max_length=200, unique=True),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='TourItinerary',
        ),
    ]
