# Generated by Django 3.2.6 on 2022-05-24 22:00

import apps.post.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slider', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='language',
            field=apps.post.models.LanguageField(choices=[('ur', 'اردو'), ('en', 'English'), ('fa', 'فارسی'), ('az', 'Azerbaijani')], default='en', max_length=2, verbose_name='language'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='photo',
            field=models.ImageField(upload_to='media/sliders'),
        ),
    ]
